<?php
define("LISTING_ADD_MSG_ERROR","Para adicionar essa foto a Minhas Imagens você deve estar logado.");
define("LISTING_ADD_MY_IMG","Adicionar a Minhas Imagens:");
define("LISTING_NEW_FOLDER","Criar nova pasta");
define("LISTING_PA","Pesquisa Avançada");
define("BUILDNAV_ANTERIOR","Anteriores");
define("BUILDNAV_PROXIMA","Pr&oacute;ximas");
define("CADASTRO_NOME_ERROR","O Nome é um campo obrigatório!");
define("CADASTRO_CPF_ERROR","O CPF digitado não é válido!");
define("CADASTRO_CNPJ_ERROR","A Razão Social é um campo obrigatório!");
define("CADASTRO_CNPJ_INVALIDO","O CNPJ digitado não é válido!");
define("CADASTRO_EMAIL_ERROR","O Email é um campo obrigatório!");
define("CADASTRO_EMAIL_CONFIRM","Informe a Confirmação de Email!");
define("CADASTRO_EMAIL_DIFF","Os emails digitados não conferem, favor digitar novamente.");
define("CADASTRO_LOGIN_ERROR","Digite o Login do usuário.");
define("CADASTRO_SENHA_ERROR","Informe a Senha!");
define("CADASTRO_SENHA2_ERROR","Informe a Confirmação de Senha!");
define("CADASTRO_SENHA_DIFF","As senhas digitadas não conferem, favor digitar novamente.");
define("CONTATO_NOME_ERROR","O Nome é um campo obrigatório!");
define("CONTATO_EMAIL_ERROR","O Email é um campo obrigatório!");
define("RECAPTCHA_ERROR","Dado de verificação não foi inserido corretamente.");
define("ENVIARPASTA_EMAIL_ERROR","O Email é um campo obrigatório!");
define("ENVIARPASTA_MENSAGEM_ERROR","A Mensagem é um campo obrigatório!");
define("ENVIARPASTA_ASSUNTO_ERROR","O Assunto é um campo obrigatório!");
define("ENVIAIMAGEM_NOME_ERROR","O Nome é um campo obrigatório!");
define("ENVIAIMAGEM_EMAIL_ERROR","O Email é um campo obrigatório!");
define("ENVIAIMAGEM_MENSAGEM_ERROR","A Mensagem é um campo obrigatório!");
define("ENVIAIMAGEM_ASSUNTO_ERROR","O Assunto é um campo obrigatório!");
define("FILTRO_FILTRO","Filtro");
define("LOGIN_LOGIN_ERROR","O Login é um campo obrigatório!");
define("LOGIN_SENHA_ERROR","A Senha é um campo obrigatório!");
define("LOGIN_EMAIL_ERROR","O Email é um campo obrigatório!");
define("LOGIN_LOGIN_INVALID","Usuário não encontrado!");
define("LOGIN_SENHA_INVALID","Senha incorreta!");
define("PASTAS_CRIAR_PASTA","Pasta criada com sucesso!");
define("PASTAS_MESCLAR_PASTA","Pasta mesclada com sucesso!");
define("PASTAS_RENOMEAR_PASTA","Pasta renomeada com sucesso!");
define("NEWLETTER_EMAIL_ERROR","O Email é um campo obrigatório!");
define("NEWLETTER_CONFIRMACAO","Pedido de cadastro na newsletter realizado.");
define("SCRIPT_SELECIONAR_TODOS","Selecionar Todos");
define("SCRIPT_ESTADO","Estado");
define("SCRIPT_SELECIONADO","selecionados");
define("SCRIPT_IMAGEM_ADD","Imagem Adicionada na Pasta.");
define("SCRIPT_TODOS","Todos");
define("SCRIPT_BLOCKER","Realizando sua pesquisa. Por favor, aguarde.");
define("MINHASIMAGENS_SELECIONAR_UMA_MSG","Você deve selecionar pelo menos uma foto!");
define("MINHASIMAGENS_CONFIRMA_MSG","Confirma exclusão?");
define("MINHASIMAGENS_SELECIONAR_MAISDEUMA_MSG","Somente uma foto por vez!");
define("MINHASIMAGENS_MULTIPLODOWNLOAD_WARN","Aviso!\\n\\rRecomendamos baixar apenas 15 arquivos simultaneamente.");
define("MINHASPASTAS_ALTERARCADASTRO_MSG","Alteração de cadastro realizada com sucesso!");
define("MINHASPASTAS_PASTALDEL_MSG","Pasta(s) deletadas com sucesso!");
define("MINHASPASTAS_PASTANOVA","Pasta Nova");
define("MINHASPASTAS_PASTAUNIDA","Pasta Unida");
define("MINHASPASTAS_COTAR_MSG","Pasta adicionada com sucesso. Visite a seção COTAÇÃO para concluir o processo.");
define("MINHASPASTAS_CARRINHO_MSG","Pasta enviada para o carrinho de compras.");
define("MINHASPASTAS_SELECIONAR_UMA_MSG","Você deve selecionar pelo menos uma pasta!");
define("MINHASPASTAS_CONFIRMA_MSG","Confirma exclusão?");
define("MINHASPASTAS_ENVIARUMA_MSG","Envie somente uma pasta por vez!");
define("MINHASPASTAS_SELECIONAR_DUAS_MSG","Você deve selecionar pelo duas uma pasta!");
define("MINHASPASTAS_RENOMEIE_UMA_MSG","Renomeie somente uma pasta por vez!");
define("DETAILS_RESOLUCAO","Resolução Original");
define("DETAILS_CODEC","Codec");
define("DETAILS_FPS","FPS");
define("DETAILS_AUDIO","Audio");
define("DETAILS_DIMENSAO","Dimensões da imagem");
define("DETAILS_DIMENSAO_FOTO","Caso necessite esse arquivo em outras dimensões, <a href=\"contato.php\">entre em contato.</a>");
define("DETAILS_COTACAO","Foto adicionada com sucesso.\\n**Visite a seção COTAÇÃO para concluir o processo.** ");
define("DETAILS_ORIGINAL","original digital");
define("DETAILS_LOCAL","Local");
define("DETAILS_PAIS","País");
define("PARTBUSCA_","PARTBUSCA_");
define("PARTBUSCA_FRACAO","fração");
define("PARTBUSCA_NAO","não");
define("PARTBUSCA_PC","palavra-chave");
define("PARTBUSCA_TOMBO","tombo");
//define("PARTBUSCA_PC","pc");
define("PARTBUSCA_ASSUNTO","assunto");
define("PARTBUSCA_EXTRA","extra");
define("PARTBUSCA_CIDADE","cidade");
define("PARTBUSCA_ESTADO","estado");
define("PARTBUSCA_ID_ESTADO","id_estado");
define("PARTBUSCA_PAIS","país");
define("PARTBUSCA_ID_TEMAS","id_temas");
define("PARTBUSCA_TEMAS","temas");
define("PARTBUSCA_ID_AUTOR","id_autor");
define("PARTBUSCA_EMAIL_ID","email");
define("PARTBUSCA_FILTRO_DIREITO_AUT","Direito Imagem");
define("PARTBUSCA_FILTRO_ID_TEMA","Tema");
define("PARTBUSCA_FILTRO_ID_AUTOR","Autor");
define("CARRINHO_BLOQ_COMPRA_BTN","Selecione uso para todas as imagens para finalizar a compra!");
define("CARRINHO_COMPRA_BTN","Finalizar compra");
define("CARRINHO_CONTINUA_BTN","Continuar comprando");
define("CARRINHO_VAZIO","N&atilde;o h&aacute; itens no carrinho");
define("CARRINHO_MOEDA","GBP");
define("CARRINHO_TIPO_PRODUTO","imagem");
define("CADASTRO_DUP_EMAIL_ERROR","Email já cadastrado");
define("CADASTRO_DUP_LOGIN_ERROR","Login já cadastrado");
define("LISTING_DIRETO_IMG","OBS: USO DE IMAGEM AUTORIZADO");
define("LISTING_DIRETO_IMG_ACRESCIMO","OBS: USO DE IMAGEM AUTORIZADO - ACRÉSCIMO DE 100% SOBRE O VALOR DE TABELA");
?>