<?php
define("LISTING_ADD_MSG_ERROR","To add this image to your folders you must login first.");
define("LISTING_ADD_MY_IMG","Add to My Folders:");
define("LISTING_NEW_FOLDER","Create new folder");
define("LISTING_PA","Advanced search");
define("BUILDNAV_ANTERIOR","Previous");
define("BUILDNAV_PROXIMA","Next");
define("CADASTRO_NOME_ERROR","You must provide a name");
define("CADASTRO_CPF_ERROR","O CPF digitado não é válido!");
define("CADASTRO_CNPJ_ERROR","A Razão Social é um campo obrigatório!");
define("CADASTRO_CNPJ_INVALIDO","O CNPJ digitado não é válido!");
define("CADASTRO_EMAIL_ERROR","You must provide an e-mail");
define("CADASTRO_EMAIL_CONFIRM","Confirm your e-mail");
define("CADASTRO_EMAIL_DIFF","The e-mail provided does not match, please type it again.");
define("CADASTRO_LOGIN_ERROR","Type in your login information.");
define("CADASTRO_SENHA_ERROR","Type in your password");
define("CADASTRO_SENHA2_ERROR","Confirm your password");
define("CADASTRO_SENHA_DIFF","The password provided does not match, please type it again.");
define("CONTATO_NOME_ERROR","You must provide a name");
define("CONTATO_EMAIL_ERROR","You must provide an e-mail");
define("RECAPTCHA_ERROR","Please type in the verification code.");
define("ENVIARPASTA_EMAIL_ERROR","You must provide an e-mail");
define("ENVIARPASTA_MENSAGEM_ERROR","Type in your message");
define("ENVIARPASTA_ASSUNTO_ERROR","Enter a subject to your message");
define("ENVIAIMAGEM_NOME_ERROR","You must provide a name");
define("ENVIAIMAGEM_EMAIL_ERROR","You must provide an e-mail.");
define("ENVIAIMAGEM_MENSAGEM_ERROR","Type in your message");
define("ENVIAIMAGEM_ASSUNTO_ERROR","Enter a subject to your message");
define("FILTRO_FILTRO","Filters");
define("LOGIN_LOGIN_ERROR","You must provide a login");
define("LOGIN_SENHA_ERROR","You must provide a password");
define("LOGIN_EMAIL_ERROR","You must provide an e-mail");
define("LOGIN_LOGIN_INVALID","Login/Password does not match");
define("LOGIN_SENHA_INVALID","Login/Password does not match");
define("PASTAS_CRIAR_PASTA","Folder created successfully");
define("PASTAS_MESCLAR_PASTA","Folders merged successfully");
define("PASTAS_RENOMEAR_PASTA","Folder renamed successfully");
define("NEWLETTER_EMAIL_ERROR","You must provide an e-mail.");
define("NEWLETTER_CONFIRMACAO","Thank you for subscribing with us!");
define("SCRIPT_SELECIONAR_TODOS","Select all");
define("SCRIPT_ESTADO","State");
define("SCRIPT_SELECIONADO","selected");
define("SCRIPT_IMAGEM_ADD","Media added to your folder");
define("SCRIPT_TODOS","All");
define("SCRIPT_BLOCKER","Searching database. Please wait");
define("MINHASIMAGENS_SELECIONAR_UMA_MSG","You must select at least one image/video");
define("MINHASIMAGENS_CONFIRMA_MSG","Are you sure you want to delete?");
define("MINHASIMAGENS_SELECIONAR_MAISDEUMA_MSG","You cannot select more than one");
define("MINHASIMAGENS_MULTIPLODOWNLOAD_WARN","Warning! We recommend you download a maximum of 15 files at the same time");
define("MINHASPASTAS_ALTERARCADASTRO_MSG","Your registration has been updated");
define("MINHASPASTAS_PASTALDEL_MSG","Folder removed successfully");
define("MINHASPASTAS_PASTANOVA","New Folder");
define("MINHASPASTAS_PASTAUNIDA","Merged Folder");
define("MINHASPASTAS_COTAR_MSG","Files(s) successfully added to your cart.");
define("MINHASPASTAS_CARRINHO_MSG","Folder sent to your shopping cart.");
define("MINHASPASTAS_SELECIONAR_UMA_MSG","You must select at least one folder.");
define("MINHASPASTAS_CONFIRMA_MSG","Are you sure you want to delete?");
define("MINHASPASTAS_ENVIARUMA_MSG","You can only sent one folder at a time");
define("MINHASPASTAS_SELECIONAR_DUAS_MSG","You must select at least two folder to merge.");
define("MINHASPASTAS_RENOMEIE_UMA_MSG","You can only rename one folder at a time.");
define("DETAILS_RESOLUCAO","Source resolution");
define("DETAILS_CODEC","Codec");
define("DETAILS_FPS","FPS");
define("DETAILS_AUDIO","Audio");
define("DETAILS_DIMENSAO","Image size");
define("DETAILS_DIMENSAO_FOTO","<a href=\"contato.php\">Contact us</a> if you require a larger file");
define("DETAILS_COTACAO","Foto adicionada com sucesso.\\n**Visite a seção COTAÇÃO para concluir o processo.** ");
define("DETAILS_ORIGINAL","Digital source");
define("DETAILS_LOCAL","Local");
define("DETAILS_PAIS","Country");
define("PARTBUSCA_","PARTBUSCA_");
define("PARTBUSCA_FRACAO","fraction");
define("PARTBUSCA_NAO","exclude");
define("PARTBUSCA_PC","keyword");
define("PARTBUSCA_TOMBO","code");
//define("PARTBUSCA_PC","pc");
define("PARTBUSCA_ASSUNTO","Subject");
define("PARTBUSCA_EXTRA","Extra information");
define("PARTBUSCA_CIDADE","City");
define("PARTBUSCA_ESTADO","State");
define("PARTBUSCA_ID_ESTADO","id_estado");
define("PARTBUSCA_PAIS","Country");
define("PARTBUSCA_ID_TEMAS","id_temas");
define("PARTBUSCA_TEMAS","Categories");
define("PARTBUSCA_ID_AUTOR","id_autor");
define("PARTBUSCA_EMAIL_ID","email");
define("PARTBUSCA_FILTRO_DIREITO_AUT","Model Release");
define("PARTBUSCA_FILTRO_ID_TEMA","Categories");
define("PARTBUSCA_FILTRO_ID_AUTOR","Author");
define("CARRINHO_BLOQ_COMPRA_BTN","You must provide an usage description to your media");
define("CARRINHO_COMPRA_BTN","Proceed to checkout");
define("CARRINHO_CONTINUA_BTN","Continue browsing");
define("CARRINHO_VAZIO","Your shopping cart is empty");
define("CARRINHO_MOEDA","£");
define("CARRINHO_TIPO_PRODUTO","Digital Image");
define("ECOMMERCE_EMAIL_SUBJECT","Your order has been confirmed");
define("ECOMMERCE_EMAIL_SENDER","Pulsar Images <contact@pulsarimages.com>");
define("CADASTRO_DUP_EMAIL_ERROR","Email already exists");
define("CADASTRO_DUP_LOGIN_ERROR","Login already exists");
define("LISTING_DIRETO_IMG","OBS: USO DE IMAGEM AUTORIZADO");
define("LISTING_DIRETO_IMG_ACRESCIMO","OBS: USO DE IMAGEM AUTORIZADO - ACRÉSCIMO DE 100% SOBRE O VALOR DE TABELA");
?>